### ISSUE TITLE
STDEV.S function v STDEV.P function 

### ISSUE THREAD

**Issue by jcampbellsmith** [mncoppola/ChronoPlotter#3]
I ran ChronoPlotter today on some data I collected this morning. In Excel I only use the STDEV.P function and this gives me a lower SD than the ChronoPlotter calculation.

The STDEV. P function is used when your data represents the entire population. The STDEV. S function is used when your data is a sample of the entire population. 

.pdf shows my data entry.
[Extract page.pdf](https://github.com/mncoppola/ChronoPlotter/files/7145554/Extract.page.pdf)
Excel shows my own calculation.
[Book1.xlsx](https://github.com/mncoppola/ChronoPlotter/files/7145563/Book1.xlsx)

**Comment by mncoppola** [comment]
Hi, the sample standard deviation (STDEV.S) is the proper calculation to use in this instance. The population stdev should only be used if we've collected every shot the rifle has ever and can ever shoot. In our case we're collecting a smaller sample of shots looking to estimate what future shots will do, so we need to use the sample stdev.

https://stats.stackexchange.com/questions/485326/confused-when-to-use-population-vs-sample-standard-deviation-in-engineering-test/485355#485355

If you re-calculate with STDEV.S the numbers should agree with ChronoPlotter
